//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inedo.BuildMasterExtensions.Oracle.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inedo.BuildMasterExtensions.Oracle.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE &quot;__BuildMaster_DbSchemaChanges&quot; (
        ///  &quot;Numeric_Release_Number&quot; NUMBER NOT NULL,
        ///  &quot;Script_Id&quot; INTEGER NOT NULL,
        ///  &quot;Script_Sequence&quot; INTEGER NOT NULL,
        ///
        ///  &quot;Script_Name&quot; NVARCHAR2(50) NOT NULL,
        ///  &quot;Executed_Date&quot; DATE NOT NULL,
        ///  &quot;Success_Indicator&quot; CHAR(1) NOT NULL,
        ///
        ///  CONSTRAINT &quot;__BldMstr_DbSchemaChangesPK&quot;
        ///    PRIMARY KEY (&quot;Numeric_Release_Number&quot;, &quot;Script_Id&quot;, &quot;Script_Sequence&quot;)
        ///)
        ///.
        /// </summary>
        internal static string Initialize1 {
            get {
                return ResourceManager.GetString("Initialize1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO &quot;__BuildMaster_DbSchemaChanges&quot;
        ///  (&quot;Numeric_Release_Number&quot;, &quot;Script_Id&quot;, &quot;Script_Sequence&quot;, &quot;Script_Name&quot;, &quot;Executed_Date&quot;, &quot;Success_Indicator&quot;)
        ///VALUES
        ///  (0, 0, 1, &apos;CREATE TABLE __BuildMaster_DbSchemaChanges&apos;, CURRENT_DATE, &apos;Y&apos;)
        ///.
        /// </summary>
        internal static string Initialize2 {
            get {
                return ResourceManager.GetString("Initialize2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE SEQUENCE &quot;__BuildMaster_DbSchema_Seq&quot;
        ///  START WITH 2
        ///  INCREMENT BY 1
        ///  NOMAXVALUE
        ///  NOCACHE.
        /// </summary>
        internal static string Initialize3 {
            get {
                return ResourceManager.GetString("Initialize3", resourceCulture);
            }
        }
    }
}
